# This is an example goreleaser.yaml file with some sane defaults.
# Make sure to check the documentation at http://goreleaser.com
before:
  hooks:
    # you may remove this if you don't use vgo
    - go mod download
build:
  env:
  - CGO_ENABLED=0
  goos:
    - darwin
    - linux
    - windows
    - freebsd
archive:
  format: tar.gz
  format_overrides:
  - goos: windows
    format: zip
  replacements:
    freebsd: FreeBSD
    darwin: Darwin
    linux: Linux
    windows: Windows
    386: i386
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
release:
  draft: true
