sudo: false
language: go
go:
  - 1.10.x
install:
  - go get -u github.com/golang/dep/cmd/dep
  - go get -u github.com/laher/goxc
  - dep ensure

script:
  - goxc -bc="linux, darwin, freebsd, windows"
