version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.10
    working_directory: /go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}
    steps:
      - checkout
      - run: go get -u github.com/golang/dep/cmd/dep
      - run: go get -u github.com/laher/goxc
      - run: dep ensure
      - run: goxc -bc="linux, darwin, freebsd, windows"
      - run: go build
      - run: ./azure-blob-uploader -account-name ${ACCOUNT_NAME} -account-key ${ACCOUNT_KEY} -c hoge -f azure-blob-uploader
